config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "wallets#index"

  resources :wallets, only: [:index, :create, :destroy] do
    collection do
      delete 'delete_purple'
      delete 'delete_blue'
      delete 'delete_pink'
      delete 'delete_all'
    end
  end

  resources :users, only: [:edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :wallets

  validates :name, presence: true
  validates :balance, presence: true

end

app/models/wallet.rb
class Wallet < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :price, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  # ログイン済ユーザーのみにアクセスを許可
  before_action :authenticate_user!
  # gem devise関連の遷移を行った際
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :balance])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update]


  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :balance)
  end

  def set_user
    @user = User.find(current_user.id)
  end

end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController

  # # ログイン済ユーザーのみにアクセスを許可
  # before_action :authenticate_user!
  before_action :move_to_index, except: :home

  
  def index
    @user = User.find(current_user.id)

    @wallet = Wallet.new
    @wallets = Wallet.where(user_id: "#{(current_user.id)}").order("created_at DESC")

    # 各色によって分けられたそれぞれの金額の合計
    @yellow = @wallets.sum(:price)
    @purple = @wallets.where(color: '1').sum(:price)
    @blue = @wallets.where(color: '2').sum(:price)
    @pink = @wallets.where(color: '3').sum(:price)

    # ( 設定された残高 / 入力金額の総合計 ) をして割合を算出
    # 算出(Calculation) 割合(Percentage) 余り(Remainder)
    @balance = @user.balance
    @yellow_cal = ( @balance.to_f / @yellow ).to_f
    @yellow_per = 100 / @yellow_cal

    # 初期状態ではDBが空のため、エラー対策としてデフォルト値を0とする。
    if @yellow == 0
      @purple_per_total = 0
      @blue_per = 0
      @pink_per = 0
    else
      @purple_cal = ( @yellow.to_f / @purple ).to_f
      @purple_per = 100 / @purple_cal

      @blue_cal = ( @yellow.to_f / @blue ).to_f
      @blue_per = 100 / @blue_cal

      @pink_cal = ( @yellow.to_f / @pink ).to_f
      @pink_per = 100 / @pink_cal

      # 端数分は@purpleに足し、3色の合計が100%になるよう調整
      @rem = (100 - @purple_per.floor - @blue_per.floor - @pink_per.floor )
      if @purple == 0
        @blue_per = @blue_per + @rem
        @purple_per_total = 0
      else
        @purple_per_total = @purple_per + @rem
      end
    end
  end

  def create
    @wallet = Wallet.new(wallet_params)
    if @wallet.valid?
      @wallet.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    wallet = Wallet.find(params[:id])
    wallet.delete
    redirect_to root_path
  end

  def delete_all
    wallets = Wallet.where(user_id: "#{(current_user.id)}")
    wallets.delete_all
    redirect_to root_path
  end

  def delete_purple
    wallets = Wallet.where(user_id: "#{(current_user.id)}")
    wallet = wallets.where(color: '1')
    wallet.delete_all
    redirect_to root_path
  end

  def delete_blue
    wallets = Wallet.where(user_id: "#{(current_user.id)}")
    wallet = wallets.where(color: '2')
    wallet.delete_all
    redirect_to root_path
  end

  def delete_pink
    wallets = Wallet.where(user_id: "#{(current_user.id)}")
    wallet = wallets.where(color: '3')
    wallet.delete_all
    redirect_to root_path
  end


  private

  def wallet_params
    params.require(:wallet).permit(:title, :price, :color).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :home unless user_signed_in?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WalletManager
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Noto+Serif+JP:200&display=swap", :rel => "stylesheet"}/
  %body
    = yield

app/views/users/edit.html.haml
.user__home
  .user__home__title
    %p Wallet Manager
  .user__home__body
    = form_for @user do |f|
      .field-box-top
        .field.name-box
          %p 名前
          = f.text_field :name, autofocus: true
        .field.balance-box
          %p 残高
          = f.number_field :balance
      .actions
        = f.submit "設定する", class: "submit-btn"
      .signout
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "signout-btn"

app/views/wallets/_content-wrapper.html.haml
.contents__wrapper
  .leftbox
    .leftbox__top.box
      .name-box
        = current_user.name
      .config-btn
        = link_to edit_user_path(current_user) do
          %i.fas.fa-user-cog
    .leftbox__form.box
      = form_for @wallet, url: wallets_path do |f|
        .form__mask__title
          %p 購入した物を入力してください。
          = f.text_field :title, class: 'title', placeholder: '(例) りんご'
        .form__mask__price
          %p 金額を入力してください。
          = f.number_field :price, class: 'price', placeholder: '(例) 200'
        .form__mask__color
          = f.label :color, class: 'form__mask__color' do
            .purple
              = f.radio_button :color, 1, checked: "checked"
              %span PURPLE
            .blue
              = f.radio_button :color, 2
              %span BLUE
            .pink
              = f.radio_button :color, 3
              %span PINK
        = f.submit '登録', class: 'form__submit', id: 'submit'
  .contents
    .contents__main.box
      - @wallets.each do |wallet|
        .content
          - if wallet.color == 1
            .content__box
              #purple.content__box-title
                = wallet.title
              #purple.content__box-price
                = wallet.price
                %span 円
            .delete-btn
              = link_to '削除', "/wallets/#{wallet.id}", method: :delete
          - elsif wallet.color == 2
            .content__box
              #blue.content__box-title
                = wallet.title
              #blue.content__box-price
                = wallet.price
                %span 円
            .delete-btn
              = link_to '削除', "/wallets/#{wallet.id}", method: :delete
          - else
            .content__box
              #pink.content__box-title
                = wallet.title
              #pink.content__box-price
                = wallet.price
                %span 円
            .delete-btn
              = link_to '削除', "/wallets/#{wallet.id}", method: :delete
  .rightbox
    .rightbox__yellow.box
      .rightbox__yellow-top
        %p 残高設定金額
        = current_user.balance
        %span 円
      .rightbox__yellow-bottom
        %p 入力された金額の合計
        = @yellow
        %span 円
        = link_to '削除', "/wallets/delete_all", method: :delete, class: "delete-btn"
    .rightbox__purple.box
      %p PURPLEの合計金額
      = @purple
      %span 円
      = link_to '削除', "/wallets/delete_purple", method: :delete, class: "delete-btn"
    .rightbox__blue.box
      %p BLUEの合計金額
      = @blue
      %span 円
      = link_to '削除', "/wallets/delete_blue", method: :delete, class: "delete-btn"
    .rightbox__pink.box
      %P PINKの合計金額
      = @pink
      %span 円
      = link_to '削除', "/wallets/delete_pink", method: :delete, class: "delete-btn"

app/views/wallets/_header.html.haml
.header__content
  .header__content-box
    .value
      .value-yellow
        = @yellow_per.floor
        %span %
      .value-purple
        = @purple_per_total.floor
        %span %
      .value-blue
        = @blue_per.floor
        %span %
      .value-pink
        = @pink_per.floor
        %span %

app/views/wallets/index.html.haml
.wrapper
  = render "header"
  = render "content-wrapper"